vim.wo.number = true -- Line numbers
vim.o.clipboard = "unnamedplus" -- Sync clipboard between os and neovim
vim.o.ignorecase = true -- Case-insensitive searching
vim.o.smartcase = true -- Smartcase
vim.o.relativenumber = true -- Relative line numbers
vim.o.backup = false -- Don't create backup files
vim.opt.termguicolors = true -- enable highlight groups
vim.o.wrap = false -- Don't wrap lines
vim.o.linebreak = false -- Don't split words
vim.o.scrolloff = 8 -- Minimum number of lines to keep above and below cursor
vim.o.shiftwidth = 4 -- Number of spaces that a tab counts for
vim.o.tabstop = 4 -- Insert n spaces for a tab
vim.o.expandtab = true -- Convert tabs to spaces
vim.o.splitbelow = true -- All horizontal splits should go UNDER current window
vim.o.splitright = true -- All vertical splits should go to the RIGHT
vim.o.smartindent = true -- Make indenting smarter
vim.o.showmode = false -- Stop displaying "--INSERT--" etc.
vim.opt.swapfile = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.hlsearch = false
vim.opt.incsearch = true

