[font]
size = 12.0

[window]
opacity = 0.7
decorations = "None"

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.italic]
family = "JetBrainsMono"

[font.normal]
family = "JetBrainsMono"
style = "Regular"
